### PR TITLE
Use Nabu Casa TTS via Home Assistant

### PR DESCRIPTION
**Pull request by willscottuk**
This removes the dependency on the Google Translate TTS with its limited choice of voices.

### CODE REVIEW

**Comment by OverZealous** [comment]
Hey, this looks awesome! I was looking for something like this. I've reverted to the old way of doing TTS with Sonos, which seems to mess up my play config once in awhile.

Have you gotten it working yet? Are you interested in collaborating?

**Comment by willscottuk** [comment]
Hi @OverZealous - thanks for your interest, good to know it's not just me that was looking for this.

The good news is that I have got it working (and working well enough for a node.js outsider). If you'd like to try it out, there are two options - first would be cloning my repo, checking out the HASS branch & then building the docker image yourself (I'll post the additional things you need for the `options.json` line below). Otherwise, I can try to get things to a point where you can just plug the URL into Home Assistant like the base package - but that probably won't happen until the weekend. Let me know!

If you go for option 1, the additional keys you need in `options.json` are `HASS_URL` (url, including http(s):// but with no trailing /) and `HASS_TOKEN` (a long-lived API token generated from within Home Assistant.

**Comment by OverZealous** [comment]
I'll probably wait to see what you get done this weekend, but I'll be happy to help test it then, for sure!

**Comment by willscottuk** [comment]
Hi @OverZealous 

I think it's all good to go now!

So my version takes all the great work that @kevinvincent did, adds in a load of the changes that @Letrab made (including playing everywhere etc.) and then uses the Home Assistant API proxy (the changes I've made today) to add the Nabu Casa TTS as an alternative to the Google Translate TTS API (I haven't removed any of the Google TTS code, so you can use them interchangeably if you want).

It obviously requires a Nabu Casa subscription and the values for CLOUD_TTS_LANGUAGE and CLOUD_TTS_GENDER should be taken from [https://www.nabucasa.com/config/tts/](https://www.nabucasa.com/config/tts/
)

To get started, all you need to do is add my repository `https://github.com/willscottuk/hassio-addons` to your Home Assistant Supervisor.

Do let me know how you get on!

**Comment by OverZealous** [comment]
This looks great! Sorry I didn't get a chance to check this weekend, I wasn't feeling well. I'll do my best to get to it soon!

**Comment by Letrab** [comment]
Would be a nice one to PR into the original repo? @kevinvincent @willscottuk

**Comment by willscottuk** [comment]
> Would be a nice one to PR into the original repo? @kevinvincent @willscottuk 

Thanks @Letrab - happy to if @kevinvincent agrees. What I haven't done yet is test how gracefully it fails when run in regular Docker rather than HA Supervised (as all of the Nabu Casa TTS stuff depends on the API proxy)

**Comment by OverZealous** [comment]
I just got it set up, it's working great for me! I had to change some old scripts to use my external URL for sounds (I have yet to understand how the internal MP3s are supposed to work), but the Hass-based voices worked immediately and as expected.

Best of all, Sonos now supports all of my older devices, which makes this infinitely more useful for things like doorbells and house-wide announcements.

Thanks again!

**Pull request merged**
